require('options')
require('keymaps')
require('lazy-config')
require('colorscheme')
require('lsp')
require('bufferline-config')
require('mini-config')
require 'plugins.autopairs'
require('lualine-config')
require('oil-config')
